### ISSUE TITLE
Spec out current state of the http api

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/http-api-spec#7]
Current version: http://docs.ipfs.apiary.io/#
### TODO
- [ ] `add`
- [ ] `bitswap` (@dignifiedquire)
  - [ ] `bitswap stat`
  - [ ] `bitswap unwant`
  - [ ] `bitswap wantlist`
- [ ] `block` (@dignifiedquire)
  - [ ] `block get`
  - [ ] `block put`
  - [ ] `block stat`
- [x] `bootstrap` (@RichardLitt)
  - [x] `bootstrap add`
  - [x] `bootstrap list`
  - [x] `bootstrap rm`
- [x] `cat` (@RichardLitt)
- [x] `commands`
- [ ] `config`
  - [ ] `config edit`
  - [ ] `config replace`
  - [ ] `config show`
- [ ] `dht`
  - [ ] `dht findpeer`
  - [ ] `dht findprovs`
  - [ ] `dht get`
  - [ ] `dht put`
  - [ ] `dht query`
- [x] `diag`
  - [x] `diag net`
  - [x] `diag sys`
- [x] `dns`
- [ ] `file`
  - [ ] `file ls`
- [ ] `get`
- [x] `id`
- [ ] `log`
  - [ ] `log level`
  - [ ] `log tail`
- [ ] `ls`
- [ ] `mount`
- [ ] `name`
  - [ ] `name publish`
  - [ ] `name resolve`
- [ ] `object`
  - [ ] `object data`
  - [ ] `object get`
  - [ ] `object links`
  - [ ] `object new`
  - [ ] `object patch`
  - [ ] `object put`
  - [ ] `object stat`
- [ ] `pin`
  - [ ] `pin add`
  - [ ] `pin ls`
  - [ ] `pin rm`
- [x] `ping`
- [ ] `refs`
  - [ ] `refs local`
- [x] `repo`
  - [x] `repo gc`
- [x] `resolve`
- [x] `stats`
  - [x] `stats bw`
- [x] `swarm`
  - [x] `swarm addrs`
  - [x] `swarm addrs local`
  - [x] `swarm connect`
  - [x] `swarm disconnect`
  - [x] `swarm filters`
  - [x] `swarm filters add`
  - [x] `swarm filters rm`
  - [x] `swarm peers`
- [ ] `tar`
  - [ ] `tar add`
  - [ ] `tar cat`
- [x] `tour`
  - [x] `tour list`
  - [x] `tour next`
  - [x] `tour restart`
- [x] `version`

**Comment by daviddias** [comment]
Are you spec'ing out the IPFS API (as if required by a module), the HTTP API (which currently is pseudo RESTful) or the IPFS cli first?

**Comment by dignifiedquire** [comment]
@diasdavid I'm documenting all existing http methods that I can find, I started with the list I got from `ipfs commands` and go through each one of them and see if they are available, and if so how they work. All is done against the official `0.3.9` binary.

**Comment by jbenet** [comment]
cc @kyledrake

**Comment by jbenet** [comment]
@Dignifiedquire great find on apiary, im getting to love it

**Comment by daviddias** [comment]
Let's bring the list defined today at the API meeting to this repo :):)

**Comment by jbenet** [comment]
it's over at https://github.com/ipfs/api/blob/master/level1.md#ipfs-core now

**Comment by daviddias** [comment]
Link is broken, apparently was moved to -> https://github.com/ipfs/specs/tree/master/api
